### ISSUE TITLE
d.ts file compile error

### ISSUE THREAD

**Issue by mastrayer** [sendbird/SendBird-SDK-JavaScript#116]
Hi Sendbird.

Maybe, sendbird.d.ts file has typescript syntax error in 3.0.101 version.

```
declare enum MessageRequestState { NONE = 'none', PENDING = 'pending', FAILED = 'failed', SUCCEEDED = 'succeeded' }
```
I think above code occurs error.

thanks.

**Comment by Alchemist85K** [comment]
@mastrayer 
I updated d.ts file to resolve the issue. 
Could you update the latest version and try it? 
Thank you for your interest in SendBird SDK :)

**Comment by mastrayer** [comment]
@Alchemist85K 
It works!

Love sendbird.
Thanks.
