### ISSUE TITLE
Multiple new Sendbird() calls return the same object

### ISSUE THREAD

**Issue by bdrobinson** [sendbird/SendBird-SDK-JavaScript#118]
I've spotted a very odd behaviour of the `Sendbird` constructor. If I do
```js
import Sendbird from "sendbird"
const s1 = new Sendbird({appId: "aaa"})
const s2 = new Sendbird({appId: "aaa"})
```
then `s1 === s2` is `true`, which seems like very counter-intuitive behaviour for the `new Sendbird()` constructor to have? This has caused a fairly major bug in our app as we assumed that multiple calls to `new Sendbird` will return completely independent objects which could be connected and disconnected independently, which has turned out to not be the case. Could you help me understand the rationale for this behaviour? How hard would it be to change back?

I'd be happy to do a PR but it looks like the source code for this library isn't open source.

Thanks!

**Comment by erickimme** [comment]
@bdrobinson  Thank you for opening this issue and we saw that you opened up the support ticket with us. We will follow up with you directly there.

**Comment by bdrobinson** [comment]
Perfect, thanks! Yeah I wasn't sure the best place to post. Thanks for the
quick response.
