### ISSUE TITLE
Custom type for messages is not set correctly by SDK

### ISSUE THREAD

**Issue by hexadeciman** [sendbird/SendBird-SDK-JavaScript#123]
As you can see below the HTTP call gives the correct custom_type when fetching the messages using Sendbird API:
<img width="697" alt="Capture d’écran 2019-09-25 à 00 10 35" src="https://user-images.githubusercontent.com/5367205/65556871-217cf000-df29-11e9-9b0d-96332dbaf289.png">

When fetching the data using the SDK
```
this.prevMessageListQuery = group.createPreviousMessageListQuery();
this.prevMessageListQuery.limit = SB_MAX_MESSAGES_COUNT;
this.prevMessageListQuery.reverse = true;

this.prevMessageListQuery.load((messages, error) => {
  if (error) {
    observer.error(error);
    observer.complete()
  }
  console.log(messages)
  observer.next(messages);
  observer.complete();
});
```

The console log logs this:
![image](https://user-images.githubusercontent.com/5367205/65529617-c0d4bf80-def6-11e9-83c4-8e34dd9653ab.png)

You can clearly see that the customType is now text/plain.

This is how I've setup my message when sending it:
```
const params = new sb.UserMessageParams();
params.message = myMessage;
params.data = myBody;
params.customType = 'event/session'

group.sendUserMessage(params, (message, error) => {
 ....
});

```

I tried setting only the data or only the message or both, doesn't change anything. There's an issue with the js sdk, the information is lost between the HTTP call response and the SDK response.

I'm running the latest version of the sdk: 3.0.108

**Comment by AlexOrrSB** [comment]
The messages that you shared screenshots of, appear to be different messages. The channelUrl is a unique identifier for channel objects. Take another look and let us know.

**Comment by hexadeciman** [comment]
Hi @AlexOrrSB 
I uploaded the wrong screenshot you're right, I updated the screenshot that matches the logs.
The issue with custom types not being mapped correctly by the js sdk is still there.

**Comment by AlexOrrSB** [comment]
Hmm, I haven't encountered this before, and it is a bit concerning.  If you are able to reproduce this it would help if you could provide as much of the following information as possible.

If you can't reproduce this or get this information the screenshots should probably be enough to investigate further, but this would help me hopefully find a resolution a little more quickly.

- The HTTP request and response when sending the message (this may not be needed, but if can please include).
- The HTTP request and response when retrieving the message list.
- The array of messages that you logged in your second screenshot.

From our previous discussions I know that text/plain is one of the mime_types from your migration. The SendBird server wouldn't know about this, and the data would have to come from your migration activity at some point. 

It looks like you log the message list inside the callback function so ```messages``` should always match what was returned by the HTTP request. Can you confirm that the API request in your first screenshot was the one that was made by the SDK when you called ```this.prevMessageListQuery.load(...)``` ?

**Comment by hexadeciman** [comment]
> Can you confirm that the API request in your first screenshot was the one that was made by the SDK when you called
Yes I confirm.

> The HTTP request and response when sending the message (this may not be needed, but if can please include).
Using the SDK I can't see the HTTP request and response when sending the message for some reason, but here's the sdk request and response:
**SDK request param for sending the message:**
```
{
  "_message": "{\"object\":{\"id\":\"aaaaaaaaa\",\"photoUrl\":\"https://photourl.com\",\"thumbnailUrl\":\"https://session.com\",\"startDatetime\":\"2018-06-07T17:30:00.000-07:00\",\"endDatetime\":\"2018-06-07T18:00:00.000-07:00\",\"displayTime\":\"17:30 - 18:00\",\"name\":\"Open discussion - Moving forward\"}}",
  "_translationTargetLanguages": null,
  "_targetLanguages": null,
  "_data": null,
  "_customType": "event/session",
  "_mentionType": "users",
  "_metaArrayKeys": [],
  "_mentionedIds": [],
  "_mentionedUsers": null,
  "_mentionedUserIds": null,
  "_pushNotificationDeliveryOption": null
}
```
FYI this is the object constructed by doing:
`const params = new sb.UserMessageParams();`
and setting the attributes: message and customType.

**SDK response after sending the message:**
```
{
  "messageType": "user",
  "messageId": 172452714,
  "channelUrl": "sendbird_group_channel_18829153_6722adc1cd5df23f5ad518954b6b437d51d848df",
  "data": "",
  "customType": "text/plain",
  "createdAt": 1569398433638,
  "updatedAt": 0,
  "channelType": "group",
  "metaArrays": [],
  "mentionType": "users",
  "mentionedUsers": [],
  "message": "{\"object\":{\"id\":\"aaaaaaaaa\",\"photoUrl\":\"https://photourl.com\",\"thumbnailUrl\":\"https://session.com\",\"startDatetime\":\"2018-06-07T17:30:00.000-07:00\",\"endDatetime\":\"2018-06-07T18:00:00.000-07:00\",\"displayTime\":\"17:30 - 18:00\",\"name\":\"Open discussion - Moving forward\"}}",
  "_sender": {
    "isBlockedByMe": false,
    "userId": "001b0000041F6JyAAK",
    "nickname": "",
    "profileUrl": "",
    "connectionStatus": "nonavailable",
    "lastSeenAt": 0,
    "metaData": {},
    "isActive": true,
    "friendDiscoveryKey": null,
    "friendName": null
  },
  "reqId": "1569398362326",
  "translations": {},
  "requestState": "succeeded",
  "requestedMentionUserIds": [],
  "sent_at": null
}
```

Now if I try to get the messages, I can see the HTTP GET request:
/group_channels/sendbird_group_channel_18829153_6722adc1cd5df23f5ad518954b6b437d51d848df/messages?is_sdk=true&message_ts=9223372036854776000&prev_limit=20&next_limit=0&include=false&reverse=true&with_sorted_meta_array=false

I get an array of messages with this in it:
```
{
  "custom_type": "event/session",
  "mentioned_users": [],
  "translations": {},
  "updated_at": 0,
  "is_removed": false,
  "user": {
    "is_blocked_by_me": false,
    "nickname": "",
    "user_id": "001b0000041F6JyAAK",
    "profile_url": "",
    "metadata": {}
  },
  "file": {},
  "message": "{\"object\":{\"id\":\"a0W0X00000C5z2MUAR\",\"photoUrl\":\"https://photourl.com\",\"thumbnailUrl\":\"https://session.com\",\"startDatetime\":\"2018-06-07T17:30:00.000-07:00\",\"endDatetime\":\"2018-06-07T18:00:00.000-07:00\",\"displayTime\":\"17:30 - 18:00\",\"name\":\"Open discussion - Moving forward\"}}",
  "data": "",
  "type": "MESG",
  "created_at": 1569398385027,
  "mention_type": "users",
  "channel_url": "sendbird_group_channel_18829153_6722adc1cd5df23f5ad518954b6b437d51d848df",
  "message_id": 172452490
}
```

and then when I use the sdk to read the data I get:
```{
  "messageType": "user",
  "messageId": 172452490,
  "channelUrl": "sendbird_group_channel_18829153_6722adc1cd5df23f5ad518954b6b437d51d848df",
  "data": "",
  "customType": "text/plain",
  "createdAt": 1569398385027,
  "updatedAt": 0,
  "channelType": "group",
  "metaArrays": [],
  "mentionType": "users",
  "mentionedUsers": [],
  "message": "{\"object\":{\"id\":\"a0W0X00000C5z2MUAR\",\"photoUrl\":\"https://photourl.com\",\"thumbnailUrl\":\"https://session.com\",\"startDatetime\":\"2018-06-07T17:30:00.000-07:00\",\"endDatetime\":\"2018-06-07T18:00:00.000-07:00\",\"displayTime\":\"17:30 - 18:00\",\"name\":\"Open discussion - Moving forward\"}}",
  "_sender": {
    "isBlockedByMe": false,
    "userId": "001b0000041F6JyAAK",
    "nickname": "",
    "profileUrl": "",
    "connectionStatus": "nonavailable",
    "lastSeenAt": 0,
    "metaData": {},
    "isActive": true,
    "friendDiscoveryKey": null,
    "friendName": null
  },
  "reqId": "",
  "translations": {},
  "requestState": "succeeded",
  "requestedMentionUserIds": [],
  "sent_at": "Today"
}```

**Comment by AlexPrestonSB** [comment]
Hey @hexadeciman, 

We will file a ticket internally to get this resolved.

**Comment by aibek-bird** [comment]
Hello @hexadeciman,

I have checked your approach with v3.0.108 of core SDK and this sample https://github.com/sendbird/SendBird-JavaScript/tree/master/web-basic-sample. Everything worked well, the message's customType field was set successfully. Can you please provide more details such as code snippet?

Thank you

**Comment by hexadeciman** [comment]
> the message's customType field was set successfully

How do you know ? The demo app doesn't use the customType feature in Group channels.
You'd need to be able to send a custom typed message to reproduce the issue.

**Comment by aibek-bird** [comment]
Hi @hexadeciman, 

By following the steps you described, the console.log command showed the messages contained an assigned customType. 

So, in my case when I do `params.customType = 'event/session'`, the retrieved messages customType fields all reflect `event/session`.

Please, can you check one more time? Hopefully, we can solve this issue sooner.

**Comment by hexadeciman** [comment]
I'll create a stackblitz app to prove my point.
