### ISSUE TITLE
Typings for callbacks are incorrect

### ISSUE THREAD

**Issue by ben-homepass** [sendbird/SendBird-SDK-JavaScript#129]
The types for Sendbird have the parameters for callbacks in the wrong order. Each callback type has `error` as the 2nd parameter - but this is against the node convention and isn't actually what the library does. The library actually seems to stick to the node convention and passes `error` as the 1st parameter. This breaks our TypeScript project (at compile time).

**Comment by aibek-bird** [comment]
You are right @ben-homepass, the default behavior of our SDK is that error does not come first in the callbacks. However, you can easily change that if you use `setErrorFirstCallback(true)` method of SendBird class. Can you please try that and let us know if this works. Also, can you provide the version of the SendBird package you are using? FYI, with newer versions, you can use Promise pattern instead of callbacks.

**Comment by aibek-bird** [comment]
You are right @ben-homepass, the default behavior of our SDK is that error does not come first in the callbacks. However, you can easily change that if you use `setErrorFirstCallback(true)` method of SendBird class. Can you please try that and let us know if this works. Also, can you provide the version of the SendBird package you are using? FYI, with newer versions, you can use Promise pattern instead of callbacks.

**Comment by ben-homepass** [comment]
@aibek-bird Thank you for a quick reply. Ah yes, I see now in our app init we call `setErrorFirstCallback(true)`, thus the callback behaviour becomes out of alignment with the types.

We are using the latest version (`3.0.112`). When you say we can use the promise pattern instead of callbacks, do you mean using something like `Bluebird.promisify` to wrap the methods or do you mean if we don't pass a callback the methods will return a promise? If the latter is true then the typings do not reflect this.

**Comment by ben-homepass** [comment]
FYI, we tried calling `sendMessage` without a callback to see if it would return a `Promise` but it threw an error like "t is not a function".

**Comment by aibek-bird** [comment]
@ben-homepass , yes if you don't specify the callback, the Promise will be returned, and you can use `.then(res => {}).catch(err => {})` pattern in this scenario. Can you provide a code snippet or example where the `setErrorFirstCallback` is not behaving correctly? I hope we resolve this issue as soon as possible

**Comment by ben-homepass** [comment]
@aibek-bird With the below code snippet:

```typescript
const sendMessage = async (
      message: string,
      data: string,
      customType: string,
      translationTargetLanguages: Array<string>,
    ) => {
      try {
      	const promise = channel.sendUserMessage(
					message,
					data,
					customType,
					translationTargetLanguages,
				);
      	console.log('promise ->', promise);
        const response = await promise;
        console.log('response -> ', response);
        return response;
      } catch (e) {
        console.log('ERROR OCCURED IN SEND MESSAGE: ', e);
        throw e;
      }
    };
```

We get the following error:

```
ERROR OCCURED IN SEND MESSAGE:  TypeError: t is not a function
    at e.value (SendBird.min.js:6)
    at sendM$ (sagas.ts:734)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:170
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)
    at callInvokeWithMethodAndArg (runtime.js:169)
    at AsyncIterator.enqueue [as _invoke] (runtime.js:192)
    at AsyncIterator.prototype.<computed> [as next] (runtime.js:97)
    at Object.exports.async (runtime.js:216)
    at sendM (sagas.ts:727)
```

It appears that `channel.sendUserMessage` tries to call the last parameter as a function as if it is a callback.

We call `setErrorFirstCallback(true)` earlier, I'm not sure if that has an effect on the promise pattern?

**Comment by aibek-bird** [comment]
@ben-homepass, for this specific method, it does not return Promise,     https://github.com/sendbird/messaging-js/blob/7742aacbc9b6a08836f445dbc3adb8dcb8a28a0d/SendBird.d.ts#L836. Can you try it with callback? I have tested and it works fine.

**Comment by ben-homepass** [comment]
I see. I noticed you linked to the types as if to confirm that the specific method does not return a `Promise`. But if I search for `Promise` in the `sendbird.d.ts` file there are no matches whatsoever.

I've worked around the types misalignment issue by wrapping each sendbird method with `Bluebird.promisify` and casting to the correct type.

```typescript
const sendMessage = (bluebird.promisify(
      channel.sendUserMessage.bind(channel),
    ) as unknown) as (
      message: string,
      data: string,
      customType: string,
      translationTargetLanguages: Array<string>,
    ) => Promise<SB.Message>;
```

**Comment by aibek-bird** [comment]
@ben-homepass, yes you are right, we lack the description for the methods which return Promise, we soon plan to release the official API docs with that. I am glad that you have found the workaround for this issue. FYI for most of the methods (except few), you can use Promises without promisifying, as we do promisifying inside.

**Comment by ben-homepass** [comment]
Thanks for your help.
