### ISSUE TITLE
Missing dependencies in v3.0.119

### ISSUE THREAD

**Issue by mkubenka** [sendbird/SendBird-SDK-JavaScript#137]
Hello,

looks like v3.0.119 introduce new dependencies `fs` and `child_process` without correct update in package.json.

```
ERROR in ./node_modules/sendbird/SendBird.min.js
Module not found: Error: Can't resolve 'child_process' in '/root/project/node_modules/sendbird'

ERROR in ./node_modules/sendbird/SendBird.min.js
Module not found: Error: Can't resolve 'fs' in '/root/project/node_modules/sendbird'
 @ ./node_modules/sendbird/SendBird.min.js 6:5580-5593
```

**Comment by dsemennyuk** [comment]
same there!

**Comment by dsemennyuk** [comment]
@mkubenka Quick workaround until updations. Version `3.0.103` works.

**Comment by mkubenka** [comment]
@dsemennyuk Yep, thanks, we are using previous version `3.0.118` without issue. `child_process` and `fs` were introduced in `3.0.119`.

@chrisallo Any reason why those dependencies were introduced? I'm a little bit worried about security implications that `node -e` is executed...

**Comment by jadex87** [comment]
I was plagued with this for a couple days till I found this thread, so glad I'm not alone.

**Comment by Enflow-io** [comment]
> I was plagued with this for a couple days till I found this thread, so glad I'm not alone.

+ 3 hours =(

**Comment by dlai0001** [comment]
I ran into the same.  Had to revert to 3.0.118

**Comment by mkubenka** [comment]
Looks like this was fixed in one of the latest releases.
