### ISSUE TITLE
TypeScript - Getting sender userId of a message doesn't work

### ISSUE THREAD

**Issue by grug** [sendbird/SendBird-SDK-JavaScript#150]
Hi there,

In my TypeScript code, when trying to get the sender of a message, the typings suggest that `message.sender.userId` will work, but when I run this in my browser I get `Cannot read property 'sender' of undefined`. When I log the message to my console I can see that the message has this property:

<img width="299" alt="test" src="https://user-images.githubusercontent.com/2045206/82488851-8e588200-9ad8-11ea-8735-e61b1a00fce0.png">

However, I am unable to access `message._sender.userId` as I also get the same error as mentioned previously.

How am I meant to get the userId of a message?

**Comment by daibhin** [comment]
I've seen the `sender` property being replaced with `_sender` in the message object when a shallow copy of the message is made, are you mutating the message object anywhere?

**Comment by grug** [comment]
I'm not sure what changed but all of a sudden I'm able to access the sender properly. I suspect there is a 99.99% chance here that I was being an idiot 😂
