### ISSUE TITLE
Image files do not display correctly in browser

### ISSUE THREAD

**Issue by dminnick-chegg** [sendbird/SendBird-SDK-JavaScript#98]
When sending file messages, specifically image messages, via Sendbird SDK, we get a url to the image back. Navigating to that url does not work as expected

**The expected behavior:**
image renders inside the browser window

**Actual behavior:**
image downloads because browser does not recognize it as an image

**Example:** 
https://sendbird-upload.s3.amazonaws.com/0BBFB550-2648-4467-A57B-A192184522A8/upload/n/ca55a636821f4650a03902a4b67f91ed.jpg

This issue has been verified with Chrome, Firefox and Safari

Searching the web for possible causes suggest that something is incorrect about the headers Sendbird servers are returning. One suggestion was that the MIME-type might be coming in as image/x-jpg vs image/jpg. We are unable to confirm this via the chrome network tab due download requests not passing through the network tab.

**Comment by janna-sendbird** [comment]
Janna here from the Solutions Engineering team at SendBird. I'm going to open up a bug for this issue and report back here on our progress. Thank you.

**Comment by dminnick-chegg** [comment]
@Alchemist85K Would it be possible to request the file as `inline`? Perhaps passed as a query param?

**Comment by janna-sendbird** [comment]
Hi @dminnick-chegg 

Our infrastructure team has picked this up and is taking a look. I passed along your last question to them too. We'll get back to you soon.
